// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhqvljdoqhnbyikiznwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpocXZsamRvcWhuYnlpa2l6bndwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNzQyMTAsImV4cCI6MjA2NDg1MDIxMH0.yZ-KGs9ngA5E5Di5bjVM2nrJKy2xrgPztC0tPr4bXY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);